project_id = "pabdpeqliwnpbnbsawqe"
[functions.process-payment]
verify_jwt = false

[functions.process-payout]
verify_jwt = false


[functions.send-notification]
verify_jwt = false

[functions.update-tracking]
verify_jwt = false

[functions.create-social-promotion]
verify_jwt = false

[functions.courier-lockers]
verify_jwt = false

[functions.ai-sales-manager]
verify_jwt = false

[functions.verify-image]
verify_jwt = false

[functions.admin-settings-check]
verify_jwt = false


[functions.ai-maintenance]
verify_jwt = false

[functions.send-easybox-code]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
